Serial communication
Guibi1/Kwik-E-Mart pull request #4
Opened 2023-11-16 16:35 UTC by wisrom

2023-11-16 16:38 UTC, Kgo20 commented on lib/serial_serialization/Order.cpp
> +    delete[] *items;
Tu as oublié les autres pointeurs

2023-11-16 16:39 UTC, Kgo20 requested changes
Pas pire

2023-11-16 16:39 UTC, Kgo20 commented on src/mega/main.cpp
> +#define BUFFER_SIZE 511
Sort ça du main

2023-11-16 16:39 UTC, Kgo20 commented on lib/serial_serialization/Order.cpp
> +    delete[] *items;
Tu as oublié les autres pointeurs

2023-11-16 18:28 UTC, Guibi1 commented on lib/serial_serialization/Order.cpp
> +    delete[] *items;
Done

2023-11-21 23:30 UTC, Guibi1 approved these changes

2023-11-22 17:25 UTC, Kgo20 approved these changes

2023-11-22 17:25 UTC, Kgo20 approved these changes

2023-11-22 17:28 UTC, merged